# Generated by Django 3.2.5 on 2021-07-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20210706_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneImages',
            new_name='PhoneImage',
        ),
    ]
